name: Security Checks

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  security-and-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Security vulnerability scanning
      - name: Run npm audit
        run: npm audit --audit-level high

      # TODO look security scanning
      # # GitHub Security Scanning (SAST)
      # - name: Initialize CodeQL
      #   uses: github/codeql-action/init@v3
      #   with:
      #     languages: javascript

      # - name: Perform CodeQL Analysis
      #   uses: github/codeql-action/analyze@v3

      # Scans for accidentally committed secrets
      # Scans only the diff between the previous commit and current HEAD
      - name: Run TruffleHog OSS (Diff Scan)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.before }}
          head: HEAD
          extra_args: --debug --only-verified
        if: github.event_name == 'push' && github.event.before != '0000000000000000000000000000000000000000'

      # Scans the diff between base and head of the PR
      - name: Run TruffleHog OSS (PR Scan)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --debug --only-verified
        if: github.event_name == 'pull_request'
